# -*- coding: utf-8 -*-
"""CodeAlpha_Unemployment-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9yJqdPnT1DzpXdDrsSlD8txvsi2jIvW
"""

#Step 1: Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Step 2: Load Dataset

df1 = pd.read_csv('/content/Unemployment in India.csv')
df2 = pd.read_csv('/content/Unemployment_Rate_upto_11_2020.csv')

#Step 3: Check Dataset Information
df1.head()
df2.head()

print(df1.info())
print(df2.info())

print(df1.isnull().sum())
print(df2.isnull().sum())

#Step 4: Data Cleaning

# Remove spaces in column names
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# Remove missing values
df1 = df1.dropna()
df2 = df2.dropna()

# Convert Date column to datetime
df1['Date'] = pd.to_datetime(df1['Date'])
df2['Date'] = pd.to_datetime(df2['Date'])

print("Data Cleaned Successfully")

#Step 5: Statistical Summary
df1.describe()

df1['Estimated Unemployment Rate (%)'].mean()

#Step 6: Unemployment Trend Analysis
plt.figure(figsize=(12,6))

plt.plot(
    df1['Date'],
    df1['Estimated Unemployment Rate (%)']
)

plt.title('Unemployment Rate Over Time')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.xticks(rotation=45)

plt.show()

#Step 7: Covid-19 Impact Analysis

#Filter 2020 data:

covid_data = df1[df1['Date'].dt.year == 2020]

covid_data.head()

plt.figure(figsize=(12,6))

sns.lineplot(
    x='Date',
    y='Estimated Unemployment Rate (%)',
    data=covid_data
)

plt.title('Covid-19 Impact on Unemployment (2020)')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.xticks(rotation=45)

plt.show()

#Step 8: State-wise Analysis

#Find states with highest unemployment:

state_data = df1.groupby('Region')[
    'Estimated Unemployment Rate (%)'
].mean().sort_values(ascending=False)

state_data

plt.figure(figsize=(12,8))

state_data.plot(kind='bar')

plt.title('Average Unemployment Rate by State')
plt.xlabel('State')
plt.ylabel('Unemployment Rate (%)')

plt.show()

#Step 12: Seasonal Trend Analysis

#Monthly unemployment trend:

df1['Month'] = df1['Date'].dt.month

monthly_trend = df1.groupby('Month')[
    'Estimated Unemployment Rate (%)'
].mean()

plt.figure(figsize=(10,5))

monthly_trend.plot(marker='o')

plt.title('Monthly Unemployment Trend')
plt.xlabel('Month')
plt.ylabel('Average Unemployment Rate (%)')

plt.show()

#Step 13: Correlation Heatmap
plt.figure(figsize=(8,5))

sns.heatmap(
    df1.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')

plt.show()

"""
Conclusion:
Unemployment varied across Indian states.
Covid-19 had a major impact on unemployment in 2020.
Lockdown periods caused unemployment spikes.
Some regions showed consistently higher unemployment rates.
Monthly analysis revealed seasonal employment variations.

Recommendations:
Increase employment programs.
Promote skill development.
Improve economic recovery policies after crises.

"""