# -*- coding: utf-8 -*-
"""Iris_Flower_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RMET-gqvwlsAR_N8d-THlqaSrsS1Cb0i
"""

#Step 1: Import Libraries
import pandas as pd

#Step 2: Load Dataset

data = pd.read_csv("Iris.csv")

#Step 3: View Dataset
print(data.head())
print(data.info())
print(data.columns)

#Step 4: Separate Input and Output

X = data.drop(["Id", "Species"], axis=1)
y = data["Species"]

#Step 5: Split Dataset into Train and Test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

#Step 6: Create Model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

#Step 7: Train Model
model.fit(X_train, y_train)

#Step 8: Make Predictions
y_pred = model.predict(X_test)

#Step 9: Check Accuracy

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

#Step 10: Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

#Step 11: Predict New Flower
sample = [[5.1, 3.5, 1.4, 0.2]]

prediction = model.predict(sample)

print("Predicted Species:", prediction[0])

